name: CI Checks

on:
  push:
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        node: ["22", "24"]
        python: ["3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
          - node: "24"
          - python: "3.13"
          - python: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - uses: go-task/setup-task@v1
        with:
          version: "3.x"
      - name: Install dependencies
        run: |
          pip install uv
          npm i -g pnpm
      - name: Build
        run: task build
      - name: Run unit tests
        run: task test
